### PR TITLE
remove flag for 'results_from_file'

### PR DESCRIPTION
**Pull request by KPostOffice**

### CODE REVIEW

**Review by fridex — COMMENTED** [review]
Will it write to file `-` by default?

**Comment by KPostOffice** [comment]
@fridex `-` is stdout

**Review by fridex — APPROVED** [review]
lgtm :+1:

**Comment by fridex** [comment]
> @fridex `-` is stdout

Sounds good, I mixed it with `--output`. Sorry for the confusion :)

**Pull request merged**
